# Colors (Gruvbox light)

# Default colors
[colors.primary]
# hard contrast background = = '#f9f5d7'
background = '#fbf1c7'
# soft contrast background = = '#f2e5bc'
foreground = '#3c3836'

# Normal colors
[colors.normal]
black   = '#3c3836'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#fbf1c7'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#9d0006'
green   = '#79740e'
yellow  = '#b57614'
blue    = '#076678'
magenta = '#8f3f71'
cyan    = '#427b58'
white   = '#d5c4a1'
